movie/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('actor/', views.actor_index, name='actor list'),
    path('filmdetail/<int:film_num>/', views.film, name='film'),
    path('actordetail/<int:actor_num>/', views.actor, name='actor'),
    path('search/', views.search_place, name='search'),
    path('search0/', views.search, name='search')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('movie.urls')),
]

movie/models.py
from django.db import models


class Actor(models.Model):
    actor_name = models.CharField(max_length=30)
    actor_intro = models.TextField(max_length=1000, default='')
    actor_number = models.IntegerField(default=0)

    def __str__(self):
        return self.actor_name


class Movie(models.Model):
    film_name = models.CharField(max_length=30)
    film_number = models.IntegerField(default=0)
    film_intro = models.TextField(max_length=1000)
    film_year = models.CharField(max_length=10, default='')
    actor = models.ManyToManyField(Actor)

    def __str__(self):
        return self.film_name


class Comment(models.Model):
    comment = models.TextField(max_length=1000)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

movie/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from datetime import datetime
from django.core.paginator import Paginator
from django.db.models import Q

import operator

from .models import *


def index(request):
    begin = datetime.now()
    data = Movie.objects.filter().values()
    paginator = Paginator(data, 50)
    page_number = int(request.GET.get('page', 1))
    page = paginator.get_page(page_number)
    end = datetime.now()
    cost = (end - begin).total_seconds()
    page_range = range(max(1, page_number - 2), min(paginator.num_pages, page_number + 5) + 1)
    return render(request, 'movie/index.html', {'posts': page, 'cost': cost, 'page_range': page_range})


def actor_index(request):
    begin = datetime.now()
    data = Actor.objects.filter().values()
    paginator = Paginator(data, 50)
    page_number = int(request.GET.get('page', 1))
    page = paginator.get_page(page_number)
    end = datetime.now()
    cost = (end - begin).total_seconds()
    page_range = range(max(1, page_number - 2), min(paginator.num_pages, page_number + 5) + 1)
    return render(request, 'movie/actorIndex.html', {'posts': page, 'cost': cost, 'page_range': page_range})


def search_place(request):
    return render(request, 'movie/search.html')


def search(request):
    test = request.GET.get('search_class')
    key = request.GET.get('keyword')
    begin = datetime.now()
    if test == "Comment":
        comment_list = Comment.objects.filter(Q(comment__icontains=key))
        paginator = Paginator(comment_list, 25)
        page_number = int(request.GET.get('page', 1))
        page = paginator.get_page(page_number)
        end = datetime.now()
        cost = (end - begin).total_seconds()
        page_range = range(max(1, page_number - 2), min(paginator.num_pages, page_number + 5) + 1)
        return render(request, 'movie/commentIndex.html',
                      {'posts': page, 'cost': cost, 'keyword': key, 'page_range': page_range, 'type': test})

    elif test == "Movie":
        list0 = Movie.objects.filter(Q(film_name__icontains=key) | Q(actor__actor_name__icontains=key))
        film_list = list(set(list0))
        paginator = Paginator(film_list, 25)
        page_number = int(request.GET.get('page', 1))
        page = paginator.get_page(page_number)
        end = datetime.now()
        cost = (end - begin).total_seconds()
        page_range = range(max(1, page_number - 2), min(paginator.num_pages, page_number + 5) + 1)
        return render(request, 'movie/filmSearch.html',
                      {'posts': page, 'cost': cost, 'keyword': key, 'page_range': page_range, 'type': test})
    elif test == "Actor":
        list0 = Actor.objects.filter(Q(actor_name__icontains=key) | Q(movie__film_name__icontains=key))
        actor_list = list(set(list0))
        paginator = Paginator(actor_list, 25)
        page_number = int(request.GET.get('page', 1))
        page = paginator.get_page(page_number)
        end = datetime.now()
        cost = (end - begin).total_seconds()
        page_range = range(max(1, page_number - 2), min(paginator.num_pages, page_number + 5) + 1)
        return render(request, 'movie/actorSearch.html',
                      {'posts': page, 'cost': cost, 'keyword': key, 'page_range': page_range, 'type': test})



def film(request, film_num):
    return render(request, 'movie/filmdetail.html', {'post': get_object_or_404(Movie, film_number=film_num)})


def actor(request, actor_num):
    act = Actor.objects.get(actor_number=actor_num)
    ls = act.movie_set.filter()
    related_actor = []
    for a in ls:
        related_actor += a.actor.filter(~Q(actor_number=act.actor_number))
    set_a = list(set(related_actor))
    count_set_a = {}
    for item in set_a:
        count_set_a[item] = related_actor.count(item)
    sorted_list_a = sorted(count_set_a.items(), key=operator.itemgetter(1))

    result_a = []  # 存放最后的结果
    i = 0
    for item in sorted_list_a[::-1]:  # 按value值从大到小排序
        if i < 10:
            result_a.append(item)
            i += 1
    return render(request, 'movie/actordetail.html', {'post': get_object_or_404(Actor, actor_number=actor_num),
                                                      'related': result_a})

movie/templates/movie/actorIndex.html
{% extends "movie/base.html" %}
{% load static %}

{% block customStyles %}
    <link rel="stylesheet" href="{% static 'styles/posts.css' %}">
{% endblock %}

{% block main %}
    <h1 style="text-align: center;">影视列表</h1>
    <div class="container">

        {% for post in posts %}
            <div class="post row">
                <p class="col-2">
                    <a href="{% url "actor" post.actor_number %}">
                        <img src="{% static 'images/ActorPhoto/' %}{{ post.actor_number }}{{ ".jpg" }}">
                    </a>
                </p>

                <p class="col-2">
                    <a href="{% url "actor" post.actor_number %}" class="post-title">{{ post.actor_name }}</a>
                </p>
            </div>
        {% endfor %}

        <p>Find {{ posts.paginator.count }} results in {{ cost }} s,
            currently at page {{ posts.number }} / {{ posts.paginator.num_pages }}</p>

        {% if posts %}
            <nav aria-label="Page navigation" style="position: static;">
                <ul class="pagination pagination-lg justify-content-center">
                    {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?keyword={{ keyword }}&page={{ posts.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}
                    {% for num in page_range %}
                        {% if num == posts.number %}
                            <li class="page-item">
                                <a class="page-link selected" href="?keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?keyword={{ keyword }}&page={{ posts.next_page_number }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>


{% endblock %}

movie/templates/movie/actorSearch.html
{% extends "movie/base.html" %}
{% load static %}

{% block customStyles %}
    <link rel="stylesheet" href="{% static 'styles/posts.css' %}">
{% endblock %}

{% block main %}
    <h1 style="text-align: center;">影视搜索结果</h1>
    <div class="container">

        {% for post in posts %}
            <div class="post row">
                <p class="col-2">
                    <a href="{% url "actor" post.actor_number %}">
                        <img src="{% static 'images/ActorPhoto/' %}{{ post.actor_number }}{{ ".jpg" }}">
                    </a>
                </p>

                <p class="col-2">
                    <a href="{% url "actor" post.actor_number %}" class="post-title">{{ post.actor_name }}</a>
                </p>
            </div>
        {% endfor %}

        <p>With keyword {{ keyword }} in {{ type }}, Find {{ posts.paginator.count }} results in {{ cost }} s,
            currently at page {{ posts.number }} / {{ posts.paginator.num_pages }}</p>

        {% if posts %}
            <nav aria-label="Page navigation" style="position: static;">
                <ul class="pagination pagination-lg justify-content-center">
                    {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?keyword={{ keyword }}&page={{ posts.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}
                    {% for num in page_range %}
                        {% if num == posts.number %}
                            <li class="page-item">
                                <a class="page-link selected"
                                   href="?search_class=Actor&keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="?search_class=Actor&keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?search_class=Actor&keyword={{ keyword }}&page={{ posts.next_page_number }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>


{% endblock %}

movie/templates/movie/actordetail.html
{% extends "movie/base.html" %}
{% load static %}

{% block customStyles %}
    <link rel="stylesheet" href="{% static 'styles/post.css' %}">
    <link rel="stylesheet" href="{% static 'styles/posts.css' %}">
{% endblock %}

{% block main %}
    <h2 class="post-title">{{ post.actor_name }}</h2>
    <a class="post-image">
        <img src="{% static 'images/ActorPhoto/' %}{{ post.actor_number }}{{ ".jpg" }}">
    </a>
    <div class="post-content">
        <p><strong class="post-special">简介：</strong>{{ post.actor_intro }}</p>
    </div>

    <div class="post-comment">
        <strong class="post-special">参演影视：</strong>
    </div>
    {% for a in post.movie_set.filter %}
        <div class="post row">
            <p class="col-2">
                <a href="{% url "film" a.film_number %}">
                    <img src="{% static 'images/Photo/' %}{{ a.film_number }}{{ ".jpg" }}">
                </a>
            </p>

            <p class="col-2">
                <a href="{% url "film" a.film_number %}" class="post-title">{{ a.film_name }}</a>
            </p>
        </div>
    {% endfor %}
    <div class="post-comment">
        <strong class="post-special">合作演员：</strong>
    </div>
    {% for a in related %}
        <div class="post row">
            <p class="col-2">
                <a href="{% url "actor" a.0.actor_number %}">
                    <img src="{% static 'images/ActorPhoto/' %}{{ a.0.actor_number }}{{ ".jpg" }}">
                </a>
            </p>

            <p class="col-2">
                <a href="{% url "actor" a.0.actor_number %}" class="post-title">{{ a.0.actor_name }}</a>
            </p>
            <p>
                合作次数：{{ a.1 }}
            </p>
        </div>
    {% endfor %}
{% endblock %}

movie/templates/movie/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    {% block title %}
      <title>Search</title>
    {% endblock %}
    <link href="{% static 'styles/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <link rel="stylesheet" href="{% static '/styles/search.css' %}">
    <link rel="stylesheet" href="{% static 'styles/footer.css' %}">
    <link rel="stylesheet" href="{% static 'styles/nav.css' %}">
    {% block customStyles %}
    {% endblock %}
  </head>
  <body>
    <div class="main-content">
      {% block nav %}
        {% include 'movie/nav.html' %}
      {% endblock %}
      <main>
        {% block main %}
        {% endblock %}
      </main>
    </div>
    <footer>
      <p>&copy; 2020</p>
    </footer>
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'scripts/nav.js' %}"></script>
    {% block customScripts %}
    {% endblock %}
  </body>
</html>

movie/templates/movie/commentIndex.html
{% extends "movie/base.html" %}
{% load static %}

{% block customStyles %}
    <link rel="stylesheet" href="{% static 'styles/posts.css' %}">
{% endblock %}

{% block main %}
    <h1 style="text-align: center;">影评搜索结果</h1>
    <div class="container">

        <ul>
            {% for post in posts %}
                <li>
                    <div class="comments">
                        <p>
                            <a href="{% url "film" post.movie.film_number %}">{{ post.comment }}</a>
                        </p>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <p>With keyword {{ keyword }} in {{ type }}, Find {{ posts.paginator.count }} results in {{ cost }} s,
            currently at page {{ posts.number }} / {{ posts.paginator.num_pages }}</p>

        {% if posts %}
            <nav aria-label="Page navigation" style="position: static;">
                <ul class="pagination pagination-lg justify-content-center">
                    {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?search_class=Comment&keyword={{ keyword }}&page={{ posts.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}
                    {% for num in page_range %}
                        {% if num == posts.number %}
                            <li class="page-item">
                                <a class="page-link selected"
                                   href="?search_class=Comment&keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="?search_class=Comment&keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?search_class=Comment&keyword={{ keyword }}&page={{ posts.next_page_number }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>


{% endblock %}

movie/templates/movie/filmSearch.html
{% extends "movie/base.html" %}
{% load static %}

{% block customStyles %}
    <link rel="stylesheet" href="{% static 'styles/posts.css' %}">
{% endblock %}

{% block main %}
    <h1 style="text-align: center;">影视搜索结果</h1>
    <div class="container">

        {% for post in posts %}
            <div class="post row">
                <p class="col-2">
                    <a href="{% url "film" post.film_number %}">
                        <img src="{% static 'images/Photo/' %}{{ post.film_number }}{{ ".jpg" }}">
                    </a>
                </p>
                <p class="col-2">
                    <a href="{% url "film" post.film_number %}" class="post-title">{{ post.film_name }}</a>
                </p>
            </div>
        {% endfor %}

        <p>With keyword {{ keyword }} in {{ type }}, Find {{ posts.paginator.count }} results in {{ cost }} s,
            currently at page {{ posts.number }} / {{ posts.paginator.num_pages }}</p>

        {% if posts %}
            <nav aria-label="Page navigation" style="position: static;">
                <ul class="pagination pagination-lg justify-content-center">
                    {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?search_class=Movie&keyword={{ keyword }}&page={{ posts.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}
                    {% for num in page_range %}
                        {% if num == posts.number %}
                            <li class="page-item">
                                <a class="page-link selected"
                                   href="?search_class=Movie&keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="?search_class=Movie&keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?keyword={{ keyword }}&page={{ posts.next_page_number }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>


{% endblock %}

movie/templates/movie/filmdetail.html
{% extends "movie/base.html" %}
{% load static %}

{% block customStyles %}
    <link rel="stylesheet" href="{% static 'styles/post.css' %}">
    <link rel="stylesheet" href="{% static 'styles/posts.css' %}">
{% endblock %}

{% block main %}
    <h2 class="post-title">{{ post.film_name }}</h2>
    <a class="post-image">
        <img src="{% static 'images/Photo/' %}{{ post.film_number }}{{ ".jpg" }}">
    </a>
    <p class="post-info">上映时间：{{ post.film_year }}</p>
    <div class="post-content">
        <p><strong class="post-special">简介：</strong>{{ post.film_intro }}</p>
    </div>
    <div class="post-comment">
        <strong class="post-special">演员：</strong>
    </div>

    {% for a in post.actor.filter %}
        <div class="post row">
            <p class="col-2">
                <a href="{% url "actor" a.actor_number %}">
                    <img src="{% static 'images/ActorPhoto/' %}{{ a.actor_number }}{{ ".jpg" }}">
                </a>
            </p>

            <p class="col-2">
                <a href="{% url "actor" a.actor_number %}" class="post-title">{{ a.actor_name }}</a>
            </p>
        </div>
    {% endfor %}
    <div class="post-comment">
        <strong class="post-special">影评：</strong>
    </div>
    {% for a in post.comment_set.filter %}
        <div class="post-comment">
            <a>{{ a.comment }}</a>
        </div>
    {% endfor %}
{% endblock %}

movie/templates/movie/index.html
{% extends "movie/base.html" %}
{% load static %}

{% block customStyles %}
    <link rel="stylesheet" href="{% static 'styles/posts.css' %}">
{% endblock %}

{% block main %}
    <h1 style="text-align: center;">影视列表</h1>
    <div class="container">

        {% for post in posts %}
            <div class="post row">
                <p class="col-2">
                    <a href="{% url "film" post.film_number %}">
                        <img src="{% static 'images/Photo/' %}{{ post.film_number }}{{ ".jpg" }}">
                    </a>
                </p>
                <p class="col-2">
                    <a href="{% url "film" post.film_number %}" class="post-title">{{ post.film_name }}</a>
                </p>
            </div>
        {% endfor %}

        <p>Find {{ posts.paginator.count }} results in {{ cost }} s,
            currently at page {{ posts.number }} / {{ posts.paginator.num_pages }}</p>

        {% if posts %}
            <nav aria-label="Page navigation" style="position: static;">
                <ul class="pagination pagination-lg justify-content-center">
                    {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?keyword={{ keyword }}&page={{ posts.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}
                    {% for num in page_range %}
                        {% if num == posts.number %}
                            <li class="page-item">
                                <a class="page-link selected" href="?keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?keyword={{ keyword }}&page={{ num }}">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?keyword={{ keyword }}&page={{ posts.next_page_number }}"
                               aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>


{% endblock %}

movie/templates/movie/nav.html
{% load static %}
<nav class="navbar navbar-expand navbar-dark sticky-top">
    <a class="navbar-brand" href="{% url 'index' %}">
    </a>
    <div class="navbar-nav">

        <a class="button" href="http://localhost:8000/movie/">
            <button class="nav-button" id="film_list">影视列表</button>
        </a>
        <a class="button" href="http://localhost:8000/movie/actor">
            <button class="nav-button" id="actor_list">演员列表</button>
        </a>
        <a class="button" href="http://localhost:8000/movie/search">
            <button class="nav-button" id="actor_list">搜索页面</button>
        </a>
    </div>
    <div class="search-area">
        <form action="{% url 'search' %}">
            <input placeholder="Press Enter to search" name="keyword" id="search-bar" class="search-bar">
        </form>
    </div>
</nav>

movie/templates/movie/search.html
{% extends "movie/base.html" %}
{% load static %}

{% block customStyles %}
    <link rel="stylesheet" href="{% static 'styles/index.css' %}">
{% endblock %}

{% block main %}
    <div class="search-area">
    <a href="#">
    </a>
    <form action="{% url 'search' %}" method="GET">
        <select name="search_class">
            <option value="Movie">影视</option>
            <option value="Actor">演员</option>
            <option value="Comment">影评</option>
        </select>
        <input placeholder="Enter Something ..." name="keyword" id="search-bar" class="search-bar">
    </form>
  </div>
{% endblock %}